create database trailler_movie;
use trailler_movie;
create table genres(
id_genre int primary key auto_increment,
name_genre varchar(255)
);
create table directors(
id_director int primary key auto_increment,
name_director varchar(255),
image_director mediumtext
);
create table writers(
id_writer int primary key auto_increment,
name_writer varchar(255),
image_writer mediumtext
);
create table movies(
id_movie int primary key auto_increment,
title_movie varchar(255),
rating_movie double,
rank_movie int,
year_movie int,
image_movie mediumtext,
description_movie mediumtext,
traller_movie varchar(255),
id_genre int,
foreign key (id_genre) references genres(id_genre)
);
create table movie_director(
id_movie int,
id_director int,
foreign key (id_movie) references movies(id_movie),
foreign key (id_director) references directors(id_director)
);
create table movie_writer(
id_movie int,
id_writer int,
foreign key (id_movie) references movies(id_movie),
foreign key (id_writer) references writers(id_writer)
);

insert into genres(name_genre)
value ('Drama'),
('Crime'),
('Action'),
('Animation'),
('Mystery'),
('Animation'),
('Western'),
('Horror');

insert into directors(name_director, image_director)
value ('Rob Minkoff', null),
('Akira Kurosawa', null),
('David Fincher', null),
('Frank Darabont', null),
('Martin Scorsese', null),
(' Michael Curtiz', null),
('Quentin Tarantino', null),
('Ridley Scott', null),
('Roger Allers', null),
(' Roman Polanski', null),
('Sergio Leone', null),
('Steven Spielberg', null),
('Alfred Hitchcock', null),
('Bong Joon Ho', null),
('Bryan Singer', null),
('Charles Chaplin', null),
('Christopher Nolan', null),
('Damien Chazelle', null),
('Éric Toledano', null),
('Fernando Meirelles', null),
('Francis Ford Coppola', null),
('Frank Capra', null),
('Frank Darabont', null),
('George Lucas', null),
('Hayao Miyazaki', null),
('Irvin Kershner', null),
('Isao Takahata', null),
('James Cameron', null),
('Kátia Lund (co-director)', null),
('Lana Wachowski', null),
('Lilly Wachowski', null),
('Luc Besson', null),
('Martin Scorsese', null),
('Masaki Kobayashi', null),
('Milos Forman', null),
('Olivier Nakache', null),
('Peter Jackson', null),
('Robert Zemeckis', null),
('Roberto Benigni', null),
('Sidney Lumet', null),
('Tony Kaye', null);

insert into writers(name_writer, image_writer)
value ('Agenore Incrocci', null),
('Akira Kurosawa', null),
('Alan Mak', null),
('Albert Hackett ', null),
('Andrew Kevin Walker', null),
('Bo Goldman', null),
('Bob Gale', null),
('Bráulio Mantovani', null),
('Charles Chaplin', null),
('Christopher McQuarrie', null),
('Christopher Nolan', null),
('Damien Chazelle', null),
("Dan O'Bannon", null),
('Dario Argento', null),
('David McKenna', null),
('David S. Goyer', null),
('Eric Roth', null),
('Felix Chong', null),
('Fran Walsh', null),
('Frances Goodrich', null),
('Francis Ford Coppola', null),
('Frank Capra', null),
('Frank Darabont', null),
('George Lucas', null),
('Han Jin-won', null),
('Hayao Miyazaki', null),
('Hideo Oguni', null),
('Howard Koch', null),
('Irene Mecchi', null),
('Isao Takahata', null),
('James Cameron', null),
('Jim Uhls', null),
('John Logan', null),
('John Michael Hayes', null),
('Jonathan Nolan', null),
('Jonathan Roberts', null),
('Joseph Stefano', null),
('Julius J. Epstein', null),
('Lana Wachowski', null),
('Lawrence Hauben', null),
('Lawrence Kasdan', null),
('Leigh Brackett', null),
('Lilly Wachowski', null),
('Linda Woolverton', null),
('Luc Besson', null),
('Mario Puzo', null),
('Martin Scorsese', null),
('Philip G. Epstein', null),
('Philippa Boyens', null),
('Quentin Tarantino ', null),
('Robert Rodat', null),
('Robert Zemeckis', null),
('Roger Avary', null),
('Ronald Harwood', null),
('Sergio Donati', null),
('Sergio Leone', null),
('Shinobu Hashimoto', null),
('Steven Zaillian', null),
('Ted Tally', null),
('Thomas Harris', null),
('William Monahan', null),
('William Nicholson', null),
('William Wisher', null),
('Bong Joon Ho', null),
('Olivier Nakache', null),
('Éric Toledano', null),
('Vincenzo Cerami', null),
('Roberto Benigni', null),
('Reginald Rose ', null),
('Ronald Shusett', null);

insert into movies(title_movie, rating_movie, rank_movie, year_movie, image_movie, description_movie, traller_movie, id_genre)
value ("The Shawshank Redemption", 9.3, 1, 1994, 
"https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_QL75_UX380_CR0,1,380,562_.jpg", 
"Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.", "https://www.youtube.com/embed/NmzuHjWmXOc", 1 ),
("The Godfather", 9.2, 2, 1972, 
"https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_QL75_UY562_CR8,0,380,562_.jpg", 
"The aging patriarch of an organized crime dynasty in postwar New York City transfers control of his clandestine empire to his reluctant youngest son", 
"https://www.youtube.com/embed/rqGJyUB1Q3s", 2),
("The Dark Knight", 9, 3, 2008, 
"https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_QL75_UX380_CR0,0,380,562_.jpg", 
"When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.", 
"https://www.youtube.com/embed/EXeTwQWrcwY", 3),
("The Godfather Part II",9,4,1974, 
"https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_QL75_UY562_CR7,0,380,562_.jpg",
"The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.",	
"https://www.youtube.com/embed/9O1Iy9od7-A", 2),
("12 Angry Men", 9, 5, 1957, 
"https://m.media-amazon.com/images/M/MV5BMWU4N2FjNzYtNTVkNC00NzQ0LTg0MjAtYTJlMjFhNGUxZDFmXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_QL75_UX380_CR0,11,380,562_.jpg",
"The jury in a New York City murder trial is frustrated by a single member whose skeptical caution forces them to more carefully consider the evidence before jumping to a hasty verdict.", 
"https://www.youtube.com/embed/TEN-2uTi2c0", 2),
("Schindlers List", 8.9, 6, 1993, 
"https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_QL75_UX380_CR0,4,380,562_.jpg",
"In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the NazisIn German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis", 
"https://www.youtube.com/embed/gG22XNhtnoY", 1),
("The Lord of the Rings: The Return of the King", 8.9, 7, 2003,
"https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_QL75_UX380_CR0,0,380,562_.jpg", 
"Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.", 
"https://www.youtube.com/embed/y2rYRu8UW8M", 3),
("Pulp Fiction",8.8, 8, 1994, 
"https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_QL75_UY562_CR3,0,380,562_.jpg",
"The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.", 
"https://www.youtube.com/embed/5ZAhzsi1ybM", 2),
("The Lord of the Rings: The Fellowship of the Ring", 8.8, 9, 2001,
"https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_QL75_UX380_CR0,1,380,562_.jpg", 
"A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
"https://www.youtube.com/embed/_e8QGuG50ro", 1),
("The Good, the Bad and the Ugly", 8.8, 10, 1966, 
"https://m.media-amazon.com/images/M/MV5BNjJlYmNkZGItM2NhYy00MjlmLTk5NmQtNjg1NmM2ODU4OTMwXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_QL75_UX380_CR0,4,380,562_.jpg",
"A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.", 
"https://www.youtube.com/embed/WCN5JJY_wiA", 7),
("Forrest Gump", 8.8, 11, 1994, 
"https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_QL75_UY562_CR4,0,380,562_.jpg", 
"The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.", 
"https://www.youtube.com/embed/bLvqoHBptjg", 1),
("Fight Club", 8.7, 12 ,1999, 
"https://m.media-amazon.com/images/M/MV5BNDIzNDU0YzEtYzE5Ni00ZjlkLTk5ZjgtNjM3NWE4YzA3Nzk3XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_QL75_UX380_CR0,1,380,562_.jpg",
"An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.", 
"https://www.youtube.com/embed/qtRKdVHc-cE", 1),
("Inception", 8.7, 13,  2010, 
"https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_QL75_UX380_CR0,0,380,562_.jpg", 
"When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.", 
"https://www.youtube.com/embed/vKQi3bBA1y8", 3),
("The Lord of the Rings: The Two Towers", 8.7, 14, 2002, 
"https://m.media-amazon.com/images/M/MV5BZGMxZTdjZmYtMmE2Ni00ZTdkLWI5NTgtNjlmMjBiNzU2MmI5XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_QL75_UX380_CR0,14,380,562_.jpg",
"While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard.", 
"https://www.youtube.com/embed/hYcw5ksV8YQ", 3),
("Star Wars: Episode V - The Empire Strikes Back", 8.7, 15, 1980, 
"https://m.media-amazon.com/images/M/MV5BYmU1NDRjNDgtMzhiMi00NjZmLTg5NGItZDNiZjU5NTU4OTE0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_QL75_UX380_CR0,15,380,562_.jpg", 
"After the Rebels are brutally overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins Jedi training with Yoda, while his friends are pursued across the galaxy by Darth Vader and bounty hunter Boba Fett.", 
"https://www.youtube.com/embed/JNwNXF9Y6kY", 4),
("The Matrix", 8.7, 16, 1999, 
"https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_QL75_UX380_CR0,4,380,562_.jpg", 
"When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.", 
"https://www.youtube.com/embed/vKQi3bBA1y8", 3),
("Goodfellas", 8.7, 17, 1990, 
"https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjIwYjFjNmI3ZGEwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_QL75_UX380_CR0,3,380,562_.jpg", 
"The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate.", 
"https://www.youtube.com/embed/2ilzidi_J8Q", 2),
("One Flew Over the Cuckoo's Nest", 8.6, 18, 1975, 
"https://m.media-amazon.com/images/M/MV5BZjA0OWVhOTAtYWQxNi00YzNhLWI4ZjYtNjFjZTEyYjJlNDVlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_QL75_UX380_CR0,1,380,562_.jpg", 
"In the Fall of 1963, a Korean War veteran and criminal pleads insanity and is admitted to a mental institution, where he rallies up the scared patients against the tyrannical nurse.", 
"https://www.youtube.com/embed/OXrcDonY-B8", 1),
("Se7en", 8.6, 19, 1995, 
"https://m.media-amazon.com/images/M/MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_QL75_UX380_CR0,16,380,562_.jpg", 
"Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.", 
"https://www.youtube.com/embed/znmZoVkCjpI", 5),
("Seven Samurai", 8.6, 20, 1954, 
"https://m.media-amazon.com/images/M/MV5BNWQ3OTM4ZGItMWEwZi00MjI5LWI3YzgtNTYwNWRkNmIzMGI5XkEyXkFqcGdeQXVyNDY2MTk1ODk@._V1_QL75_UY562_CR11,0,380,562_.jpg", 
"Farmers from a village exploited by bandits hire a veteran samurai for protection, who gathers six other samurai to join him. As the samurai teach the peasants how to defend themselves, the village is attacked by an army of bandits.", 
"https://www.youtube.com/embed/wJ1TOratCTo", 3),
("It's a Wonderful Life", 8.6, 21, 1946, 
"https://m.media-amazon.com/images/M/MV5BZjc4NDZhZWMtNGEzYS00ZWU2LThlM2ItNTA0YzQ0OTExMTE2XkEyXkFqcGdeQXVyNjUwMzI2NzU@._V1_QL75_UY562_CR3,0,380,562_.jpg", 
"An angel is sent from Heaven to help a desperately frustrated businessman by showing him what life would have been like if he had never existed.", 
"https://www.youtube.com/embed/iLR3gZrU2Xo", 1),
("The Silence of the Lambs", 8.6, 22, 1991, 
"https://m.media-amazon.com/images/M/MV5BNjNhZTk0ZmEtNjJhMi00YzFlLWE1MmEtYzM1M2ZmMGMwMTU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_QL75_UY562_CR1,0,380,562_.jpg", 
"A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.", 
"https://www.youtube.com/embed/W6Mm8Sbe__o", 1),
("City of God", 8.6, 23, 2002,
"https://m.media-amazon.com/images/M/MV5BOTMwYjc5ZmItYTFjZC00ZGQ3LTlkNTMtMjZiNTZlMWQzNzI5XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_QL75_UX380_CR0,2,380,562_.jpg", 
"In the slums of Rio, two kids' paths diverge as one struggles to become a photographer and the other a kingpin.", 
"https://www.youtube.com/embed/dcUOO4Itgmw", 2),
("Saving Private Ryan", 8.6, 24, 1998,
"https://m.media-amazon.com/images/M/MV5BZjhkMDM4MWItZTVjOC00ZDRhLThmYTAtM2I5NzBmNmNlMzI1XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_QL75_UY562_CR1,0,380,562_.jpg", 
"Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.",
"https://www.youtube.com/embed/9CiW_DgxCnQ", 1),
("Life Is Beautiful", 8.6, 25, 1997, 
"https://m.media-amazon.com/images/M/MV5BYmJmM2Q4NmMtYThmNC00ZjRlLWEyZmItZTIwOTBlZDQ3NTQ1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_QL75_UX380_CR0,2,380,562_.jpg", 
"When an open-minded Jewish waiter and his son become victims of the Holocaust, he uses a perfect mixture of will, humor, and imagination to protect his son from the dangers around their camp.", 
"https://www.youtube.com/embed/pAYEQP8gx3w", 1),
("Interstellar", 8.6, 26, 2014, 
"https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_QL75_UX380_CR0,0,380,562_.jpg", 
"A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",  
"https://www.youtube.com/embed/4T4wxDnTYLg", 4),
("The Green Mile", 8.6, 27, 1999,
"https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_QL75_UX380_CR0,0,380,562_.jpg", 
"The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.", 
"https://www.youtube.com/embed/Ki4haFrqSrw", 2),
("Star Wars: Episode IV - A New Hope", 8.6, 28, 1977,
"https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_QL75_UX380_CR0,9,380,562_.jpg", 
"Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.", 
"https://www.youtube.com/embed/L-_xHEv0l-w", 3),
("Terminator 2: Judgment Day", 8.5, 29, 1991,
"https://m.media-amazon.com/images/M/MV5BMGU2NzRmZjUtOGUxYS00ZjdjLWEwZWItY2NlM2JhNjkxNTFmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_QL75_UX380_CR0,1,380,562_.jpg", 
"A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her ten-year-old son John from a more advanced and powerful cyborg.", 
"https://www.youtube.com/embed/CRRlbK5w8AE", 3),
("Back to the Future", 8.5, 30, 1985,
"https://m.media-amazon.com/images/M/MV5BZmU0M2Y1OGUtZjIxNi00ZjBkLTg1MjgtOWIyNThiZWIwYjRiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_QL75_UX380_CR0,14,380,562_.jpg", 
"Marty McFly, a 17-year-old high school student, is accidentally sent 30 years into the past in a time-traveling DeLorean invented by his close friend, the maverick scientist Doc Brown.", 
"https://www.youtube.com/embed/qvsgGtivCgs", 4),
("Spirited Away", 8.5, 31, 2001, 
"https://m.media-amazon.com/images/M/MV5BMjlmZmI5MDctNDE2YS00YWE0LWE5ZWItZDBhYWQ0NTcxNWRhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_QL75_UX380_CR0,0,380,562_.jpg",
"During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.", 
"https://www.youtube.com/embed/ByXuk9QqQkk", 6),
("Psycho", 8.5, 32, 1960,
"https://m.media-amazon.com/images/M/MV5BNTQwNDM1YzItNDAxZC00NWY2LTk0M2UtNDIwNWI5OGUyNWUxXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_QL75_UX380_CR0,1,380,562_.jpg", 
"A Phoenix secretary embezzles $40,000 from her employer's client, goes on the run and checks into a remote motel run by a young man under the domination of his mother.", 
"https://www.youtube.com/embed/DTJQfFQ40lI", 8),
("The Pianist", 8.5, 33, 2002, 
"https://m.media-amazon.com/images/M/MV5BOWRiZDIxZjktMTA1NC00MDQ2LWEzMjUtMTliZmY3NjQ3ODJiXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_QL75_UY562_CR14,0,380,562_.jpg", 
"A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.", 
"https://www.youtube.com/embed/BFwGqLa_oAo", 1),
("Parasite", 8.5, 34, 2019, 
"https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_QL75_UX380_CR0,0,380,562_.jpg", 
"Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.", 
"https://www.youtube.com/embed/5xH0HfJHsaY", 1),
("Léon: The Professional", 8.5, 35, 1994, 
"https://m.media-amazon.com/images/M/MV5BOTgyMWQ0ZWUtN2Q2MS00NmY0LWI3OWMtNjFkMzZlNDZjNTk0XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_QL75_UX380_CR0,2,380,562_.jpg", 
"12-year-old Mathilda is reluctantly taken in by Léon, a professional assassin, after her family is murdered. An unusual relationship forms as she becomes his protégée and learns the assassin's trade.", 
"https://www.youtube.com/embed/jawVxq1Iyl0", 3),
("The Lion King", 8.5, 36, 1994, 
"https://m.media-amazon.com/images/M/MV5BYTYxNGMyZTYtMjE3MS00MzNjLWFjNmYtMDk3N2FmM2JiM2M1XkEyXkFqcGdeQXVyNjY5NDU4NzI@._V1_QL75_UX380_CR0,1,380,562_.jpg", 
"Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.", 
"https://www.youtube.com/embed/eHcZlPpNt0Q", 6),
("Gladiator", 8.5, 37, 1994, 
"https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MjNlLTgxODEtN2U3NzIxMGVkZTA1L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_QL75_UX380_CR0,0,380,562_.jpg", 
"A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.", 
"https://www.youtube.com/embed/uvbavW31adA", 4),
("American History X", 8.5, 38, 2000, 
"https://m.media-amazon.com/images/M/MV5BZTJhN2FkYWEtMGI0My00YWM4LWI2MjAtM2UwNjY4MTI2ZTQyXkEyXkFqcGdeQXVyNjc3MjQzNTI@._V1_QL75_UX380_CR0,1,380,562_.jpg", 
"A former neo-nazi skinhead tries to prevent his younger brother from going down the same wrong path that he did.", 
"https://www.youtube.com/embed/XfQYHqsiN5g", 1),
("The Departed", 8.5, 39, 1998, 
"https://m.media-amazon.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_QL75_UY562_CR0,0,380,562_.jpg", 
"An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.", 
"https://www.youtube.com/embed/iojhqm0JTW4", 2),
("The Usual Suspects", 8.5, 40, 1995, 
"https://m.media-amazon.com/images/M/MV5BYTViNjMyNmUtNDFkNC00ZDRlLThmMDUtZDU2YWE4NGI2ZjVmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_QL75_UX380_CR0,2,380,562_.jpg", 
"A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a seemingly random police lineup.", 
"https://www.youtube.com/embed/Q0eCiCinc4E", 5),
("The Prestige", 8.5, 41, 2006, 
"https://m.media-amazon.com/images/M/MV5BMjA4NDI0MTIxNF5BMl5BanBnXkFtZTYwNTM0MzY2._V1_QL75_UX380_CR0,0,380,562_.jpg", 
"After a tragic accident, two stage magicians in 1890s London engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.", 
"https://www.youtube.com/embed/RLtaA9fFNXU", 5),
("Whiplash", 8.5, 42, 2014, 
"https://m.media-amazon.com/images/M/MV5BOTA5NDZlZGUtMjAxOS00YTRkLTkwYmMtYWQ0NWEwZDZiNjEzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_QL75_UX380_CR0,0,380,562_.jpg", 
"A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.", 
"https://www.youtube.com/embed/7d_jQycdQGo", 1),
("Casablanca", 8.5, 43, 1942, 
"https://m.media-amazon.com/images/M/MV5BY2IzZGY2YmEtYzljNS00NTM5LTgwMzUtMzM1NjQ4NGI0OTk0XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_QL75_UX380_CR0,5,380,562_.jpg", 
"A cynical expatriate American cafe owner struggles to decide whether or not to help his former lover and her fugitive husband escape the Nazis in French Morocco.", 
"https://www.youtube.com/embed/BkL9l7qovsE", 1),
("The Intouchables", 8.5, 44, 2011, 
"https://m.media-amazon.com/images/M/MV5BMTYxNDA3MDQwNl5BMl5BanBnXkFtZTcwNTU4Mzc1Nw@@._V1_QL75_UX380_CR0,0,380,562_.jpg", 
"After he becomes a quadriplegic from a paragliding accident, an aristocrat hires a young man from the projects to be his caregiver.", 
"https://www.youtube.com/embed/oK5hMNxqsFA", 1),
("Harakiri", 8.5, 45, 1962, 
"https://m.media-amazon.com/images/M/MV5BYjBmYTQ1NjItZWU5MS00YjI0LTg2OTYtYmFkN2JkMmNiNWVkXkEyXkFqcGdeQXVyMTMxMTY0OTQ@._V1_QL75_UY562_CR17,0,380,562_.jpg", 
"When a ronin requesting seppuku at a feudal lord's palace is told of the brutal suicide of another ronin who previously visited, he reveals how their pasts are intertwined - and in doing so challenges the clan's integrity.", 
"https://www.youtube.com/embed/gfABwM-Ppng", 6),
("Grave of the Fireflies", 8.5, 46, 1988, 
"https://m.media-amazon.com/images/M/MV5BZmY2NjUzNDQtNTgxNC00M2Q4LTljOWQtMjNjNDBjNWUxNmJlXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_QL75_UX380_CR0,4,380,562_.jpg", 
"A young boy and his little sister struggle to survive in Japan during World War II.", 
"https://www.youtube.com/embed/4vPeTSRd580", 6),
("Modern Times", 8.4, 47, 1936, 
"https://m.media-amazon.com/images/M/MV5BYjJiZjMzYzktNjU0NS00OTkxLWEwYzItYzdhYWJjN2QzMTRlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_QL75_UX380_CR0,15,380,562_.jpg", 
"The Tramp struggles to live in modern industrial society with the help of a young homeless woman.", 
"https://www.youtube.com/embed/GLeDdzGUTq0", 1),
("Once Upon a Time in the West", 8.4, 48, 1968, 
"https://m.media-amazon.com/images/M/MV5BODQ3NDExOGYtMzI3Mi00NWRlLTkwNjAtNjc4MDgzZGJiZTA1XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_QL75_UX380_CR0,3,380,562_.jpg", 
"A mysterious stranger with a harmonica joins forces with a notorious desperado to protect a beautiful widow from a ruthless assassin working for the railroad.", 
"https://www.youtube.com/embed/c8CJ6L0I6W8", 7),
("Rear Window", 8.4, 49, 1954, 
"https://m.media-amazon.com/images/M/MV5BNGUxYWM3M2MtMGM3Mi00ZmRiLWE0NGQtZjE5ODI2OTJhNTU0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_QL75_UY562_CR2,0,380,562_.jpg", 
"A wheelchair-bound photographer spies on his neighbors from his Greenwich Village courtyard apartment window, and becomes convinced one of them has committed murder, despite the skepticism of his fashion-model girlfriend.", 
"https://www.youtube.com/embed/m01YktiEZCw", 5),
("Alien", 8.4, 50, 1979, 
"https://m.media-amazon.com/images/M/MV5BOGQzZTBjMjQtOTVmMS00NGE5LWEyYmMtOGQ1ZGZjNmRkYjFhXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_QL75_UX380_CR0,6,380,562_.jpg", 
"The crew of a commercial spacecraft encounter a deadly lifeform after investigating an unknown transmission.", 
"https://www.youtube.com/embed/jQ5lPt9edzQ", 8);

insert into movie_director(id_movie, id_director)
value (1, 22),
(2, 20),
(3, 16),
(4, 20),
(5, 39),
(6, 11),
(7, 36),
(8, 6),
(9, 36),
(10, 10),
(11, 37),
(12, 3),
(13, 29),
(13, 30),
(14, 36),
(15, 25),
(16, 29),
(16, 30),
(17, 32),
(18, 34),
(19, 3),
(20, 2),
(21, 21),
(22, 21),
(23, 19),
(23, 28),
(24, 11),
(25, 38),
(26, 16),
(27, 22),
(28, 23),
(29, 27),
(30, 37),
(31, 24),
(32, 12),
(33, 9),
(34, 13),
(35, 31),
(36, 8),
(36, 1),
(37, 7),
(38, 40),
(39, 32),
(40, 14),
(41, 16),
(42, 17),
(43, 5),
(44, 35),
(44, 18),
(45, 33),
(46, 26),
(47, 15),
(48, 10),
(49, 12),
(50, 7);

insert into movie_writer(id_movie, id_writer)
value (1, 23),
(2, 46),
(2, 21),
(3, 35),
(3, 11),
(4, 46),
(4, 21),
(5, 69),
(6, 58),
(7, 19),
(7, 49),
(8, 50),
(8, 53),
(9, 19),
(9, 49),
(10, 1),
(11, 17),
(12, 32),
(13, 43),
(13, 39),
(14, 19),
(14, 49),
(15, 42),
(15, 41),
(15, 24),
(16, 43),
(16, 39),
(17, 47),
(18, 40),
(18, 6),
(19, 5),
(20, 2),
(20, 27),
(20, 57),
(21, 20),
(21, 6),
(21, 22),
(22, 59),
(22, 6),
(23, 8),
(24, 51),
(25, 67),
(25, 68),
(26, 11),
(26, 35),
(27, 23),
(28, 24),
(29, 31),
(29, 63),
(30, 52),
(30, 7),
(31, 26),
(32, 37),
(33, 54),
(34, 64),
(34, 25),
(35, 45),
(36, 29),
(36, 36),
(36, 44),
(37, 33),
(37, 62),
(38, 15),
(39, 61),
(39, 3),
(39, 18),
(40, 10),
(41, 35),
(41, 11),
(42, 12),
(43, 38),
(43, 48),
(43, 28),
(44, 65),
(44, 66),
(45, 57),
(46, 30),
(47, 9),
(48, 55),
(48, 56),
(48, 14),
(49, 34),
(50, 13),
(50, 7);


--  --------------------------------------------------------
use trailler_movie;
select * from directors;
select * from movie_director;
select * from movies;
select dr.name_director, image_director from directors as dr
join movie_director as md on dr.id_director = md.id_director
where md.id_movie = 13;
select * from genres;
select * from writers;
select * from movie_director;
select * from movie_writer;
select * from movies where year_movie > 2004 order by year_movie desc;
select * from movies where id_movie = 3;
insert into directors(name_director, image_director)
value ('Rob Minkoff', 'https://resizing.flixster.com/SlaN8tzPrw0Q1uVAoemZNZDdOpg=/218x280/v2/https://flxt.tmsimg.com/assets/161246_v9_bb.jpg'),
('Akira Kurosawa', 'https://m.media-amazon.com/images/M/MV5BMjE3ODQwNTY2Nl5BMl5BanBnXkFtZTcwMTI5ODM1Mw@@._V1_.jpg'),
('David Fincher', 'https://cdn.britannica.com/76/156176-050-90A36E79/Martin-Scorsese-2008.jpg?w=400&h=300&c=crop'),
('Frank Darabont', 'https://m.media-amazon.com/images/M/MV5BNjk0MTkxNzQwOF5BMl5BanBnXkFtZTcwODM5OTMwNA@@._V1_.jpg'),
('Martin Scorsese', 'https://de.web.img3.acsta.net/pictures/15/10/19/09/54/276049.jpg'),
(' Michael Curtiz', 'https://media.gettyimages.com/id/522758799/photo/portrait-of-director-michael-curtiz-holding-his-academy-award-for-his-film-casablana-with.jpg?s=612x612&w=gi&k=20&c=LoJp9lsRoui5pEr2fn2UQ-4iMzFkmUdsvpXPO1p5ReQ='),
('Quentin Tarantino', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnJkL9b-tyYzls03nWcXedCsuWrocWeIqVyvi4hTdg1l85pVbe8F0BZcvfW_1PeIkCZ6U&usqp=CAU'),
('Ridley Scott', 'https://static.wikia.nocookie.net/the-martian/images/4/49/Ridley_Scott.jpg/revision/latest?cb=20151219144441'),
('Roger Allers', 'https://media.gettyimages.com/id/454779338/photo/director-writer-roger-allers-attends-day-2-of-the-variety-studio-presented-by-moroccanoil-at.jpg?s=612x612&w=gi&k=20&c=Rj3SOKMINPPgAa8fQpHWsIL-7hVYBNsdQNBe7jnDr5s='),
(' Roman Polanski', 'https://upload.wikimedia.org/wikipedia/commons/0/06/Roman_Polanski_2011_2.jpg'),
('Sergio Leone', 'https://m.media-amazon.com/images/M/MV5BMTk4Njk5MzY3MV5BMl5BanBnXkFtZTcwMTEyMzE0NA@@._V1_.jpg'),
('Steven Spielberg', 'https://www.onthisday.com/images/people/steven-spielberg-medium.jpg'),
('Alfred Hitchcock', 'https://m.media-amazon.com/images/M/MV5BNGJkNmE4MjMtNGIzNC00NTVjLWJkNDItZTE5NTI2YmZiZDg5XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg'),
('Bong Joon Ho', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Bong_Joon-ho_2017.jpg/1200px-Bong_Joon-ho_2017.jpg'),
('Bryan Singer', 'https://upload.wikimedia.org/wikipedia/commons/0/0f/Brian_Singer_%22International_Competition_Jury%22_at_Opening_Ceremony_of_the_28th_Tokyo_International_Film_Festival_%2822427114066%29_%28cropped%29.jpg'),
('Charlie Chaplin', 'https://upload.wikimedia.org/wikipedia/commons/3/34/Charlie_Chaplin_portrait.jpg'),
('Christopher Nolan', 'https://upload.wikimedia.org/wikipedia/commons/9/95/Christopher_Nolan_Cannes_2018.jpg'),
('Damien Chazelle', 'https://upload.wikimedia.org/wikipedia/commons/5/54/Damien_Chazelle_%28cropped%29.jpg'),
('Éric Toledano', 'https://www.goldenglobes.com/sites/default/files/styles/portrait_medium/public/2021-09/eric-toledano-gettyimages-161934352.jpg?format=pjpg&auto=webp&optimize=high'),
('Fernando Meirelles', 'https://m.media-amazon.com/images/M/MV5BMTMzMDA3Mjg0N15BMl5BanBnXkFtZTYwMTc4NDIz._V1_.jpg'),
('Francis Ford Coppola', 'https://m.media-amazon.com/images/M/MV5BMTM5NDU3OTgyNV5BMl5BanBnXkFtZTcwMzQxODA0NA@@._V1_.jpg'),
('Frank Capra', 'https://flxt.tmsimg.com/assets/21686_v9_ba.jpg'),
('Frank Darabont', 'https://m.media-amazon.com/images/M/MV5BNjk0MTkxNzQwOF5BMl5BanBnXkFtZTcwODM5OTMwNA@@._V1_.jpg'),
('George Lucas', 'https://static.wikia.nocookie.net/starwars/images/e/e3/Lucas.jpg/revision/latest?cb=20080819165433'),
('Hayao Miyazaki', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Hayao_Miyazaki_201211.jpg/1200px-Hayao_Miyazaki_201211.jpg'),
('Irvin Kershner', 'https://upload.wikimedia.org/wikipedia/en/f/f7/Irvin_Kershner.jpg'),
('Isao Takahata', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Isao_Takahata.jpg/200px-Isao_Takahata.jpg'),
('James Cameron', 'https://upload.wikimedia.org/wikipedia/commons/f/fe/James_Cameron_by_Gage_Skidmore.jpg'),
('Kátia Lund (co-director)', 'https://www.themoviedb.org/t/p/w500/8jNK0JjXe6e47G9VgBtGutLadKK.jpg'),
('Lana Wachowski', 'https://m.media-amazon.com/images/M/MV5BMjEzMTc2MDQ5OV5BMl5BanBnXkFtZTcwNjkzNDY0OA@@._V1_.jpg'),
('Lilly Wachowski', 'https://m.media-amazon.com/images/M/MV5BMTU1Mjc1MjkzNV5BMl5BanBnXkFtZTgwOTc1NDQ1ODE@._V1_.jpg'),
('Luc Besson', 'https://m.media-amazon.com/images/M/MV5BMTAwNzE4Njg0NTFeQTJeQWpwZ15BbWU3MDk0MDEyMDc@._V1_.jpg'),
('Martin Scorsese', 'https://upload.wikimedia.org/wikipedia/commons/1/1c/Martin_Scorsese_Berlinale_2010_%28cropped2%29.jpg'),
('Masaki Kobayashi', 'https://upload.wikimedia.org/wikipedia/commons/0/06/Masaki_Kobayashi.jpg'),
('Milos Forman', 'https://upload.wikimedia.org/wikipedia/commons/d/d0/Milos_Forman.jpg'),
('Olivier Nakache', 'https://flxt.tmsimg.com/assets/502753_v9_bb.jpg'),
('Peter Jackson', 'https://upload.wikimedia.org/wikipedia/commons/4/4a/Peter_Jackson_SDCC_2014.jpg'),
('Robert Zemeckis', 'https://flxt.tmsimg.com/assets/1983_v9_bc.jpg'),
('Roberto Benigni', 'https://upload.wikimedia.org/wikipedia/commons/2/27/Roberto_Benigni_2021_%28cropped%29.jpg'),
('Sidney Lumet', 'https://cdn.britannica.com/93/208793-050-3E4EC101/Sidney-Lumet-Academy-Award-lifetime-achievement-2005.jpg'),
('Tony Kaye', 'https://flxt.tmsimg.com/assets/157305_v9_ba.jpg');
insert into writers(name_writer, image_writer)
value ('Agenore Incrocci', 'https://movieplayer.net-cdn.it/t/images/2003/05/03/agenore-incrocci-12545_jpg_170x0_crop_q85.jpg'),
('Akira Kurosawa', 'https://m.media-amazon.com/images/M/MV5BMjE3ODQwNTY2Nl5BMl5BanBnXkFtZTcwMTI5ODM1Mw@@._V1_.jpg'),
('Alan Mak', 'https://upload.wikimedia.org/wikipedia/commons/b/bb/Official_portrait_of_Alan_Mak_crop_2.jpg'),
('Albert Hackett ', 'https://resizing.flixster.com/-imh_zptrcun7Eo56_Ch86uLyeA=/218x280/v2/https://flxt.tmsimg.com/assets/373232_v9_ba.jpg'),
('Andrew Kevin Walker', 'https://flxt.tmsimg.com/assets/74255_v9_ba.jpg'),
('Bo Goldman', 'https://www.goldenglobes.com/sites/default/files/styles/portrait_medium/public/nomination/cover_images/1993_gg50_bo_goldman_screenplay-scent_of_a_womanng.jpg?format=pjpg&auto=webp&optimize=high'),
('Bob Gale', 'https://ichef.bbci.co.uk/images/ic/336xn/p026dl15.jpg'),
('Bráulio Mantovani', 'https://www.ccxp.com.br/media/04400362000.jpg'),
('Charlie Chaplin', 'https://upload.wikimedia.org/wikipedia/commons/3/34/Charlie_Chaplin_portrait.jpg'),
('Christopher McQuarrie', 'https://flxt.tmsimg.com/assets/207636_v9_bb.jpg'),
('Christopher Nolan', 'https://m.media-amazon.com/images/M/MV5BNjE3NDQyOTYyMV5BMl5BanBnXkFtZTcwODcyODU2Mw@@._V1_FMjpg_UX1000_.jpg'),
('Damien Chazelle', 'https://upload.wikimedia.org/wikipedia/commons/5/54/Damien_Chazelle_%28cropped%29.jpg'),
("Dan O'Bannon", 'https://upload.wikimedia.org/wikipedia/commons/6/64/Dan_O%27Bannon.jpg'),
('Dario Argento', 'https://flxt.tmsimg.com/assets/73579_v9_bb.jpg'),
('David McKenna', 'https://stunewsnewport.com/images/editorial/nov27C/Take-Five-David-McKenna.jpg'),
('David S. Goyer', 'https://upload.wikimedia.org/wikipedia/commons/d/dd/David_Goyer.jpg'),
('Eric Roth', 'https://media.vanityfair.com/photos/6238cef602e811f070077ba5/master/pass/vf-322-roth-001.png'),
('Felix Chong', 'https://www.themoviedb.org/t/p/w500/AwiN7Um3loYamJ4F413fNelveoT.jpg'),
('Fran Walsh', 'https://upload.wikimedia.org/wikipedia/commons/5/51/Fran_Walsh_DNZM_%28cropped%29.jpg'),
('Frances Goodrich', 'https://resizing.flixster.com/5qqzwp_KUI8zz05zTvNmQ6lEF3g=/218x280/v2/https://flxt.tmsimg.com/assets/370685_v9_ba.jpg'),
('Francis Ford Coppola', 'https://upload.wikimedia.org/wikipedia/commons/0/05/Francis_Ford_Coppola_2011_CC.jpg'),
('Frank Capra', 'https://flxt.tmsimg.com/assets/21686_v9_ba.jpg'),
('Frank Darabont', 'https://www.austinchronicle.com/imager/b/newfeature/1375091/b92b/Frank_Darabont_1.jpeg'),
('George Lucas', 'https://cdn.britannica.com/74/200574-050-CBF1BF4B/George-Lucas-2017.jpg'),
('Han Jin-won', 'https://cdn.celpox.com/bby_uploads/celeb/8d6ac3b5ea65dfadca20109c325d903c.jpg'),
('Hayao Miyazaki', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Hayao_Miyazaki_201211.jpg/1200px-Hayao_Miyazaki_201211.jpg'),
('Hideo Oguni', 'https://www.themoviedb.org/t/p/w500/y0tQBvlY2laUovsnBHzFWRLewrU.jpg'),
('Howard Koch', 'https://resizing.flixster.com/Cj7Nny4l1hBNcaxeZIHtVeFoUVo=/218x280/v2/https://flxt.tmsimg.com/assets/141838_v9_ba.jpg'),
('Irene Mecchi', 'https://static.wikia.nocookie.net/lionking/images/c/c8/Irene_Mecchi.png/revision/latest?cb=20190304153947'),
('Isao Takahata', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Isao_Takahata.jpg/200px-Isao_Takahata.jpg'),
('James Cameron', 'https://cdn.britannica.com/84/160284-050-695B1DE3/James-Cameron-2012.jpg'),
('Jim Uhls', 'https://live.staticflickr.com/5230/5631388147_f9e1e9c47b_b.jpg'),
('John Logan', 'https://flxt.tmsimg.com/assets/152679_v9_bb.jpg'),
('John Michael Hayes', 'https://upload.wikimedia.org/wikipedia/commons/8/82/Dr_John_Hayes_ForMemRS.jpg'),
('Jonathan Nolan', 'https://flxt.tmsimg.com/assets/477325_v9_bb.jpg'),
('Jonathan Roberts', 'https://www.wikidancesport.com/Attachments/Instructors/Jonathan%20Roberts/jonathan_roberts.jpg'),
('Joseph Stefano', 'https://upload.wikimedia.org/wikipedia/en/9/9f/Joseph_Stefano.jpg'),
('Julius J. Epstein', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDElH4F8qvM2eSBETJc1UB4gLuBwu3Pc4lL4HrnqMMlpyuJCSbNQ2ZXygz0yxbCnsIYcA&usqp=CAU'),
('Lana Wachowski', 'https://m.media-amazon.com/images/M/MV5BMjEzMTc2MDQ5OV5BMl5BanBnXkFtZTcwNjkzNDY0OA@@._V1_.jpg'),
('Lawrence Hauben', 'https://images.mubicdn.net/images/cast_member/4922/cache-209000-1489644318/image-w856.jpg'),
('Lawrence Kasdan', 'https://static.wikia.nocookie.net/starwars/images/5/5c/LawrenceKasdan.jpg/revision/latest?cb=20130127002218'),
('Leigh Brackett', 'https://m.media-amazon.com/images/M/MV5BMTU3NGE5MmQtMjdkMC00ODlkLTk5MjUtYTNkMzk3MDIwYmI4XkEyXkFqcGdeQXVyMTcyODY2NDQ@._V1_.jpg'),
('Lilly Wachowski', 'https://m.media-amazon.com/images/M/MV5BMTU1Mjc1MjkzNV5BMl5BanBnXkFtZTgwOTc1NDQ1ODE@._V1_.jpg'),
('Linda Woolverton', 'https://static.wikia.nocookie.net/disney/images/a/ad/Linda_Woolverton.jpg/revision/latest?cb=20180416131735'),
('Luc Besson', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Luc_Besson_by_Gage_Skidmore.jpg/640px-Luc_Besson_by_Gage_Skidmore.jpg'),
('Mario Puzo', 'https://upload.wikimedia.org/wikipedia/commons/4/48/Mario_Puzo_1972_%28cropped%29.jpg'),
('Martin Scorsese', 'https://cdn.britannica.com/76/156176-050-90A36E79/Martin-Scorsese-2008.jpg'),
('Philip G. Epstein', 'https://www.mtishows.com/sites/default/files/profile/juliusjepstein.jpg?download=1'),
('Philippa Boyens', 'https://m.media-amazon.com/images/M/MV5BMTUwNTcwMjE3M15BMl5BanBnXkFtZTYwNDc4NTgz._V1_FMjpg_UX1000_.jpg'),
('Quentin Tarantino ', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnJkL9b-tyYzls03nWcXedCsuWrocWeIqVyvi4hTdg1l85pVbe8F0BZcvfW_1PeIkCZ6U&usqp=CAU'),
('Robert Rodat', 'https://m.media-amazon.com/images/M/MV5BZjE5NTVjMjctYjRmMi00NmI0LWI0M2MtYjFhYzQ2NzQxZTkxXkEyXkFqcGdeQXVyMjQwMDg0Ng@@._V1_.jpg'),
('Robert Zemeckis', 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Robert_Zemeckis_%22The_Walk%22_at_Opening_Ceremony_of_the_28th_Tokyo_International_Film_Festival_%2821835891403%29_%28cropped%29.jpg'),
('Roger Avary', 'https://images.mubicdn.net/images/cast_member/2221/cache-1057-1478101707/image-w856.jpg?size=800x'),
('Ronald Harwood', 'https://m.media-amazon.com/images/M/MV5BMjAyMTI4NTM0M15BMl5BanBnXkFtZTYwMzMxOTI4._V1_.jpg'),
('Sergio Donati', 'https://images.mubicdn.net/images/cast_member/2995/cache-367103-1535618725/image-w856.jpg?size=800x'),
('Sergio Leone', 'https://flxt.tmsimg.com/assets/170605_v9_ba.jpg'),
('Shinobu Hashimoto', 'https://i.guim.co.uk/img/media/c1e19a350ae987da7afb30f66b046cf82c89481a/0_0_557_789/master/557.jpg?width=300&quality=85&auto=format&fit=max&s=14722393846985f2ddac6e67f3ba2d42'),
('Steven Zaillian', 'https://m.media-amazon.com/images/M/MV5BMTM2NTgzMDYxOF5BMl5BanBnXkFtZTcwNTQ2ODQyNw@@._V1_.jpg'),
('Ted Tally', 'https://flxt.tmsimg.com/assets/221420_v9_ba.jpg'),
('Thomas Harris', 'https://m.media-amazon.com/images/M/MV5BNDYwZTY3YWYtOTdmNi00Njc1LWEyOTUtNzFjZTBhMjU2YmUwXkEyXkFqcGdeQXVyNDkzNTM2ODg@._V1_UY1200_CR600,0,630,1200_AL_.jpg'),
('William Monahan', 'https://m.media-amazon.com/images/M/MV5BNzU5NjU2NzUyMF5BMl5BanBnXkFtZTgwMTE1ODU2MzE@._V1_.jpg'),
('William Nicholson', 'https://upload.wikimedia.org/wikipedia/commons/1/13/William_Nicholson_b1753.jpg'),
('William Wisher', 'https://images.mubicdn.net/images/cast_member/23862/cache-245412-1502324035/image-w856.jpg'),
('Bong Joon Ho', 'https://kenh14cdn.com/thumb_w/660/2020/2/10/3984-1-15813346759441253821617.jpg'),
('Olivier Nakache', 'https://m.media-amazon.com/images/M/MV5BMjI4MzIxMTQ1MV5BMl5BanBnXkFtZTcwNDk4NzgxOA@@._V1_.jpg'),
('Éric Toledano', 'https://resizing.flixster.com/BAihxE7dUmmDkRT1hOX2rDlSjYE=/218x280/v2/https://flxt.tmsimg.com/assets/502752_v9_ba.jpg'),
('Vincenzo Cerami', 'https://resizing.flixster.com/Gwz5exRRoac08pFpm4o1vcTsNJY=/218x280/v2/https://flxt.tmsimg.com/assets/214599_v9_ba.jpg'),
('Roberto Benigni', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Roberto_Benigni-5274.jpg/1200px-Roberto_Benigni-5274.jpg'),
('Reginald Rose ', 'https://scottross79.files.wordpress.com/2021/04/reginald-rose-cropped.jpg'),
('Ronald Shusett', 'https://www.themoviedb.org/t/p/w500/110MIPIAkTd1TjJy3Q4sdubF2mw.jpg');
insert into writers(name_writer, image_writer)
value ('Agenore Incrocci', 'https://movieplayer.net-cdn.it/t/images/2003/05/03/agenore-incrocci-12545_jpg_170x0_crop_q85.jpg'),
('Akira Kurosawa', 'https://m.media-amazon.com/images/M/MV5BMjE3ODQwNTY2Nl5BMl5BanBnXkFtZTcwMTI5ODM1Mw@@._V1_.jpg'),
('Alan Mak', 'https://upload.wikimedia.org/wikipedia/commons/b/bb/Official_portrait_of_Alan_Mak_crop_2.jpg'),
(4, 'https://resizing.flixster.com/-imh_zptrcun7Eo56_Ch86uLyeA=/218x280/v2/https://flxt.tmsimg.com/assets/373232_v9_ba.jpg'),
(5, 'https://flxt.tmsimg.com/assets/74255_v9_ba.jpg'),
(6, 'https://www.goldenglobes.com/sites/default/files/styles/portrait_medium/public/nomination/cover_images/1993_gg50_bo_goldman_screenplay-scent_of_a_womanng.jpg?format=pjpg&auto=webp&optimize=high'),
(7, 'https://ichef.bbci.co.uk/images/ic/336xn/p026dl15.jpg'),
(8, 'https://www.ccxp.com.br/media/04400362000.jpg'),
(9, 'https://upload.wikimedia.org/wikipedia/commons/3/34/Charlie_Chaplin_portrait.jpg'),
(10, 'https://flxt.tmsimg.com/assets/207636_v9_bb.jpg'),
(11, 'https://m.media-amazon.com/images/M/MV5BNjE3NDQyOTYyMV5BMl5BanBnXkFtZTcwODcyODU2Mw@@._V1_FMjpg_UX1000_.jpg'),
(12, 'https://upload.wikimedia.org/wikipedia/commons/5/54/Damien_Chazelle_%28cropped%29.jpg'),
(13, 'https://upload.wikimedia.org/wikipedia/commons/6/64/Dan_O%27Bannon.jpg'),
(14, 'https://flxt.tmsimg.com/assets/73579_v9_bb.jpg'),
(15, 'https://stunewsnewport.com/images/editorial/nov27C/Take-Five-David-McKenna.jpg'),
(16, 'https://upload.wikimedia.org/wikipedia/commons/d/dd/David_Goyer.jpg'),
(17, 'https://media.vanityfair.com/photos/6238cef602e811f070077ba5/master/pass/vf-322-roth-001.png'),
(18, 'https://www.themoviedb.org/t/p/w500/AwiN7Um3loYamJ4F413fNelveoT.jpg'),
(19, 'https://upload.wikimedia.org/wikipedia/commons/5/51/Fran_Walsh_DNZM_%28cropped%29.jpg'),
(20, 'https://resizing.flixster.com/5qqzwp_KUI8zz05zTvNmQ6lEF3g=/218x280/v2/https://flxt.tmsimg.com/assets/370685_v9_ba.jpg'),
(21, 'https://upload.wikimedia.org/wikipedia/commons/0/05/Francis_Ford_Coppola_2011_CC.jpg'),
(22, 'https://flxt.tmsimg.com/assets/21686_v9_ba.jpg'),
(23, 'https://www.austinchronicle.com/imager/b/newfeature/1375091/b92b/Frank_Darabont_1.jpeg'),
(24, 'https://cdn.britannica.com/74/200574-050-CBF1BF4B/George-Lucas-2017.jpg'),
(25, 'https://cdn.celpox.com/bby_uploads/celeb/8d6ac3b5ea65dfadca20109c325d903c.jpg'),
(26, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Hayao_Miyazaki_201211.jpg/1200px-Hayao_Miyazaki_201211.jpg'),
(27, 'https://www.themoviedb.org/t/p/w500/y0tQBvlY2laUovsnBHzFWRLewrU.jpg'),
(28, 'https://resizing.flixster.com/Cj7Nny4l1hBNcaxeZIHtVeFoUVo=/218x280/v2/https://flxt.tmsimg.com/assets/141838_v9_ba.jpg'),
(29, 'https://static.wikia.nocookie.net/lionking/images/c/c8/Irene_Mecchi.png/revision/latest?cb=20190304153947'),
(30, 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Isao_Takahata.jpg/200px-Isao_Takahata.jpg'),
(31, 'https://cdn.britannica.com/84/160284-050-695B1DE3/James-Cameron-2012.jpg'),
(32, 'https://live.staticflickr.com/5230/5631388147_f9e1e9c47b_b.jpg'),
(33, 'https://flxt.tmsimg.com/assets/152679_v9_bb.jpg'),
(34, 'https://upload.wikimedia.org/wikipedia/commons/8/82/Dr_John_Hayes_ForMemRS.jpg'),
(35, 'https://flxt.tmsimg.com/assets/477325_v9_bb.jpg'),
(36, 'https://www.wikidancesport.com/Attachments/Instructors/Jonathan%20Roberts/jonathan_roberts.jpg'),
(37, 'https://upload.wikimedia.org/wikipedia/en/9/9f/Joseph_Stefano.jpg'),
(38, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDElH4F8qvM2eSBETJc1UB4gLuBwu3Pc4lL4HrnqMMlpyuJCSbNQ2ZXygz0yxbCnsIYcA&usqp=CAU'),
(39, 'https://m.media-amazon.com/images/M/MV5BMjEzMTc2MDQ5OV5BMl5BanBnXkFtZTcwNjkzNDY0OA@@._V1_.jpg'),
(40, 'https://images.mubicdn.net/images/cast_member/4922/cache-209000-1489644318/image-w856.jpg'),
(41, 'https://static.wikia.nocookie.net/starwars/images/5/5c/LawrenceKasdan.jpg/revision/latest?cb=20130127002218'),
(42, 'https://m.media-amazon.com/images/M/MV5BMTU3NGE5MmQtMjdkMC00ODlkLTk5MjUtYTNkMzk3MDIwYmI4XkEyXkFqcGdeQXVyMTcyODY2NDQ@._V1_.jpg'),
(43, 'https://m.media-amazon.com/images/M/MV5BMTU1Mjc1MjkzNV5BMl5BanBnXkFtZTgwOTc1NDQ1ODE@._V1_.jpg'),
(44, 'https://static.wikia.nocookie.net/disney/images/a/ad/Linda_Woolverton.jpg/revision/latest?cb=20180416131735'),
(45, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Luc_Besson_by_Gage_Skidmore.jpg/640px-Luc_Besson_by_Gage_Skidmore.jpg'),
(46, 'https://upload.wikimedia.org/wikipedia/commons/4/48/Mario_Puzo_1972_%28cropped%29.jpg'),
(47, 'https://cdn.britannica.com/76/156176-050-90A36E79/Martin-Scorsese-2008.jpg'),
(48, 'https://www.mtishows.com/sites/default/files/profile/juliusjepstein.jpg?download=1'),
(49, 'https://m.media-amazon.com/images/M/MV5BMTUwNTcwMjE3M15BMl5BanBnXkFtZTYwNDc4NTgz._V1_FMjpg_UX1000_.jpg'),
(50, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnJkL9b-tyYzls03nWcXedCsuWrocWeIqVyvi4hTdg1l85pVbe8F0BZcvfW_1PeIkCZ6U&usqp=CAU'),
(51, 'https://m.media-amazon.com/images/M/MV5BZjE5NTVjMjctYjRmMi00NmI0LWI0M2MtYjFhYzQ2NzQxZTkxXkEyXkFqcGdeQXVyMjQwMDg0Ng@@._V1_.jpg'),
(52, 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Robert_Zemeckis_%22The_Walk%22_at_Opening_Ceremony_of_the_28th_Tokyo_International_Film_Festival_%2821835891403%29_%28cropped%29.jpg'),
(53, 'https://images.mubicdn.net/images/cast_member/2221/cache-1057-1478101707/image-w856.jpg?size=800x'),
(54, 'https://m.media-amazon.com/images/M/MV5BMjAyMTI4NTM0M15BMl5BanBnXkFtZTYwMzMxOTI4._V1_.jpg'),
(55, 'https://images.mubicdn.net/images/cast_member/2995/cache-367103-1535618725/image-w856.jpg?size=800x'),
(56, 'https://flxt.tmsimg.com/assets/170605_v9_ba.jpg'),
(57, 'https://i.guim.co.uk/img/media/c1e19a350ae987da7afb30f66b046cf82c89481a/0_0_557_789/master/557.jpg?width=300&quality=85&auto=format&fit=max&s=14722393846985f2ddac6e67f3ba2d42'),
(58, 'https://m.media-amazon.com/images/M/MV5BMTM2NTgzMDYxOF5BMl5BanBnXkFtZTcwNTQ2ODQyNw@@._V1_.jpg'),
(59, 'https://flxt.tmsimg.com/assets/221420_v9_ba.jpg'),
(60, 'https://m.media-amazon.com/images/M/MV5BNDYwZTY3YWYtOTdmNi00Njc1LWEyOTUtNzFjZTBhMjU2YmUwXkEyXkFqcGdeQXVyNDkzNTM2ODg@._V1_UY1200_CR600,0,630,1200_AL_.jpg'),
(61, 'https://m.media-amazon.com/images/M/MV5BNzU5NjU2NzUyMF5BMl5BanBnXkFtZTgwMTE1ODU2MzE@._V1_.jpg'),
(62, 'https://upload.wikimedia.org/wikipedia/commons/1/13/William_Nicholson_b1753.jpg'),
(63, 'https://images.mubicdn.net/images/cast_member/23862/cache-245412-1502324035/image-w856.jpg'),
(64, 'https://kenh14cdn.com/thumb_w/660/2020/2/10/3984-1-15813346759441253821617.jpg'),
(65, 'https://m.media-amazon.com/images/M/MV5BMjI4MzIxMTQ1MV5BMl5BanBnXkFtZTcwNDk4NzgxOA@@._V1_.jpg'),
(66, 'https://resizing.flixster.com/BAihxE7dUmmDkRT1hOX2rDlSjYE=/218x280/v2/https://flxt.tmsimg.com/assets/502752_v9_ba.jpg'),
(67, 'https://resizing.flixster.com/Gwz5exRRoac08pFpm4o1vcTsNJY=/218x280/v2/https://flxt.tmsimg.com/assets/214599_v9_ba.jpg'),
(68, 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Roberto_Benigni-5274.jpg/1200px-Roberto_Benigni-5274.jpg'),
(69, 'https://scottross79.files.wordpress.com/2021/04/reginald-rose-cropped.jpg'),
(70, 'https://www.themoviedb.org/t/p/w500/110MIPIAkTd1TjJy3Q4sdubF2mw.jpg');
select * from writers;
use trailler_movie;
select wr.id_writer, wr.name_writer, wr.image_writer from writers as wr
join movie_writer as mw on wr.id_writer = mw.id_writer
where mw.id_movie = 13;
select count(*) from movies;
SELECT * FROM movies LIMIT 0, 20;
select * from movies where id_genre = 3;
select name_genre from genres where id_genre = 3;
select count(*) from movies where id_genre = 3;
select * from movies where title_movie like "The%";
create table account(
	id_acc int auto_increment primary key, 
    username varchar(45), 
    password varchar(45), 
    isClient tinyint, 
    isAdmin tinyint
);
insert into account(username, password, isClient, isAdmin)
	values ("chinhlv", "chinhlv", 0, 1),
		("anhquoc", "anhquoc", 1, 0),
        ("thuanky", "thuanky", 1, 0),
        ("totrinh", "totrinh", 1, 0);
insert into account(username, password, isClient, isAdmin)
	values ("quocanh", "quocanh", 0, 1),
		("minhlanh", "minhlanh", 1, 0),
        ("hoanghai", "hoanghai", 1, 0),
        ("vanminh", "vanminh", 1, 0);